{"level":50,"time":1725877269943,"pid":10816,"hostname":"Transport17","err":{"type":"NotFoundException","message":"Record not found","stack":"NotFoundException: Record not found\n    at PermissionsRepository.<anonymous> (D:\\NodeApps\\chat\\app-backend-sql-db\\src\\modules\\permissions\\permissions.repository.ts:30:13)\n    at Generator.next (<anonymous>)\n    at fulfilled (D:\\NodeApps\\chat\\app-backend-sql-db\\dist\\modules\\permissions\\permissions.repository.js:17:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","response":{"type":"Object","message":"Record not found","stack":"","error":"Not Found","statusCode":404},"status":404,"options":{},"name":"NotFoundException"},"msg":"An error occurred while deleting permission with id 400"}
{"level":50,"time":1725877269946,"pid":10816,"hostname":"Transport17","msg":"HTTP Exception: Record not found"}
{"level":50,"time":1725877766000,"pid":14716,"hostname":"Transport17","err":{"type":"NotFoundException","message":"Record not found","stack":"NotFoundException: Record not found\n    at RolesRepository.<anonymous> (D:\\NodeApps\\chat\\app-backend-sql-db\\src\\modules\\roles\\roles.repository.ts:47:13)\n    at Generator.next (<anonymous>)\n    at fulfilled (D:\\NodeApps\\chat\\app-backend-sql-db\\dist\\modules\\roles\\roles.repository.js:17:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","response":{"type":"Object","message":"Record not found","stack":"","error":"Not Found","statusCode":404},"status":404,"options":{},"name":"NotFoundException"},"msg":"An error occurred while deleting role with id 397"}
{"level":50,"time":1725877766002,"pid":14716,"hostname":"Transport17","msg":"HTTP Exception: Record not found"}
{"level":50,"time":1725877862143,"pid":14716,"hostname":"Transport17","msg":"HTTP Exception: Expected double-quoted property name in JSON at position 57"}
{"level":50,"time":1725877915205,"pid":14716,"hostname":"Transport17","err":{"type":"Error","message":"Cannot query across many-to-many for property permissions","stack":"Error: Cannot query across many-to-many for property permissions\n    at UpdateQueryBuilder.createPropertyPath (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\QueryBuilder.ts:1416:27)\n    at UpdateQueryBuilder.createUpdateExpression (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:493:18)\n    at UpdateQueryBuilder.getQuery (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:53:21)\n    at UpdateQueryBuilder.getQueryAndParameters (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\QueryBuilder.ts:495:28)\n    at UpdateQueryBuilder.execute (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:142:50)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"An error occurred while updating role with id 4"}
{"level":50,"time":1725879218242,"pid":24996,"hostname":"Transport17","err":{"type":"Error","message":"Cannot query across many-to-many for property permissions","stack":"Error: Cannot query across many-to-many for property permissions\n    at UpdateQueryBuilder.createPropertyPath (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\QueryBuilder.ts:1416:27)\n    at UpdateQueryBuilder.createUpdateExpression (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:493:18)\n    at UpdateQueryBuilder.getQuery (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:53:21)\n    at UpdateQueryBuilder.getQueryAndParameters (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\QueryBuilder.ts:495:28)\n    at UpdateQueryBuilder.execute (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:142:50)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"An error occurred while updating role with id 4"}
{"level":50,"time":1725879459286,"pid":36436,"hostname":"Transport17","msg":"HTTP Exception: email must be an email,password must be a string"}
{"level":50,"time":1725879477739,"pid":36436,"hostname":"Transport17","err":{"type":"QueryFailedError","message":"duplicate key value violates unique constraint \"UQ_97672ac88f789774dd47f7c8be3\"","stack":"QueryFailedError: duplicate key value violates unique constraint \"UQ_97672ac88f789774dd47f7c8be3\"\n    at PostgresQueryRunner.query (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\driver\\src\\driver\\postgres\\PostgresQueryRunner.ts:331:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at InsertQueryBuilder.execute (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\InsertQueryBuilder.ts:163:33)\n    at SubjectExecutor.executeInsertOperations (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\persistence\\src\\persistence\\SubjectExecutor.ts:435:42)\n    at SubjectExecutor.execute (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\persistence\\src\\persistence\\SubjectExecutor.ts:137:9)\n    at EntityPersistExecutor.execute (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\persistence\\src\\persistence\\EntityPersistExecutor.ts:182:21)","query":"INSERT INTO \"users\"(\"name\", \"email\", \"password\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3, $4, $5) RETURNING \"id\", \"created_at\", \"updated_at\"","parameters":["Testing User","testinguser@gmail.com","12345","2024-09-09T10:57:57.680Z","2024-09-09T10:57:57.680Z"],"driverError":{"type":"DatabaseError","message":"duplicate key value violates unique constraint \"UQ_97672ac88f789774dd47f7c8be3\"","stack":"error: duplicate key value violates unique constraint \"UQ_97672ac88f789774dd47f7c8be3\"\n    at D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\pg\\lib\\client.js:526:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at PostgresQueryRunner.query (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\driver\\src\\driver\\postgres\\PostgresQueryRunner.ts:260:25)\n    at InsertQueryBuilder.execute (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\query-builder\\src\\query-builder\\InsertQueryBuilder.ts:163:33)\n    at SubjectExecutor.executeInsertOperations (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\persistence\\src\\persistence\\SubjectExecutor.ts:435:42)\n    at SubjectExecutor.execute (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\persistence\\src\\persistence\\SubjectExecutor.ts:137:9)\n    at EntityPersistExecutor.execute (D:\\NodeApps\\chat\\app-backend-sql-db\\node_modules\\typeorm\\persistence\\src\\persistence\\EntityPersistExecutor.ts:182:21)","length":243,"name":"error","severity":"ERROR","code":"23505","detail":"Key (email)=(testinguser@gmail.com) already exists.","schema":"public","table":"users","constraint":"UQ_97672ac88f789774dd47f7c8be3","file":"nbtinsert.c","line":"673","routine":"_bt_check_unique"},"length":243,"severity":"ERROR","code":"23505","detail":"Key (email)=(testinguser@gmail.com) already exists.","schema":"public","table":"users","constraint":"UQ_97672ac88f789774dd47f7c8be3","file":"nbtinsert.c","line":"673","routine":"_bt_check_unique"},"msg":"An error occurred while creating user"}
{"level":50,"time":1725879477740,"pid":36436,"hostname":"Transport17","msg":"HTTP Exception: duplicate key value violates unique constraint \"UQ_97672ac88f789774dd47f7c8be3\""}
{"level":50,"time":1725880827724,"pid":16484,"hostname":"Transport17","msg":"HTTP Exception: Unauthorized"}
{"level":50,"time":1725987738277,"pid":10908,"hostname":"Transport17","msg":"HTTP Exception: Unauthorized"}
{"level":50,"time":1726053167685,"pid":22152,"hostname":"Transport17","msg":"HTTP Exception: Unauthorized"}
{"level":50,"time":1726133433990,"pid":30444,"hostname":"Transport17","msg":"HTTP Exception: duplicate key value violates unique constraint \"UQ_97672ac88f789774dd47f7c8be3\""}
